### PR TITLE
add `initialDelay` option to delay showcase initialization.

### PR DESCRIPTION
**Pull request by arielserafini**

### CODE REVIEW

**Comment by Skyost** [comment]
Seems good to me, have you tested it ?

**Comment by arielserafini** [comment]
I have tested it, yes, but ended up using the `duration` property on slides themselves (see the other 2 commits).

I have also added support for builder functions, because for my use case I needed to change slides only when clicking a button inside of the speech bubble widget I'm using.

I understand these changes might be too specific, so please take a look and see if it makes sense to include these changes in the library.

**Comment by Skyost** [comment]
I'm gonna check it tomorrow. Thanks for your contribution !

**Comment by Skyost** [comment]
I've checked your commits and well, I see nothing wrong with adding more features to this plugin (and on top of that, they are optional).

Is [this comment](https://github.com/Skyost/BubbleShowcase/pull/4/files#diff-321b083207fb50cf7e8a98582b33cb6cR27) still right ?

**Pull request merged**
